### ISSUE TITLE
sm64rt crashes with access violation immediately upon launch with new AMD drivers

### ISSUE THREAD

**Issue by landesherr** [DarioSamo/sm64rt#67]
**Bug Description**
Immediately upon opening the program, an access violation/segfault is triggered upon initialization of the rendering engine (`RT64_CreateDevice`), and the program is terminated. This is quite possibly just a problem with the latest AMD drivers, as the AV occurs within `amdxc64.dll`, but there is still the possibility that the problem could be starting upstream.

**Additional context**
GPU: AMD RX6900XT
Driver Version: 24.3.1
OS: Windows 10 22H2 x64
CPU: AMD Ryzen 7900

Debug backtrace from GDB:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffc5fabb390 in amdxc64!?load_object_data@?$iserializer@Vsc_xml_iarchive@@U_SC_SI_PS_ATTR_CH_ENTRY@@@detail@archive@boost@@UEBAXAEAVbasic_iarchive@234@PEAXI@Z ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
(gdb) backtrace
#0  0x00007ffc5fabb390 in amdxc64!?load_object_data@?$iserializer@Vsc_xml_iarchive@@U_SC_SI_PS_ATTR_CH_ENTRY@@@detail@archive@boost@@UEBAXAEAVbasic_iarchive@234@PEAXI@Z ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#1  0x00007ffc5fabc668 in amdxc64!?load_object_data@?$iserializer@Vsc_xml_iarchive@@U_SC_SI_PS_ATTR_CH_ENTRY@@@detail@archive@boost@@UEBAXAEAVbasic_iarchive@234@PEAXI@Z ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#2  0x00007ffc5fab96ac in amdxc64!?load_object_data@?$iserializer@Vsc_xml_iarchive@@U_SC_SI_PS_ATTR_CH_ENTRY@@@detail@archive@boost@@UEBAXAEAVbasic_iarchive@234@PEAXI@Z ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#3  0x00007ffc5f91db21 in amdxc64!??0?$singleton@V?$extended_type_info_typeid@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@serialization@boost@@@serialization@boost@@IEAA@XZ ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#4  0x00007ffc5f9200ce in amdxc64!??0?$singleton@V?$extended_type_info_typeid@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocat--Type <RET> for more, q to quit, c to continue without paging--
or@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@serialization@boost@@@serialization@boost@@IEAA@XZ () from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#5  0x00007ffc5f94291d in amdxc64!??0?$singleton@V?$extended_type_info_typeid@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@serialization@boost@@@serialization@boost@@IEAA@XZ ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#6  0x00007ffc5f926797 in amdxc64!??0?$singleton@V?$extended_type_info_typeid@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@serialization@boost@@@serialization@boost@@IEAA@XZ ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#7  0x00007ffc5f89c75a in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#8  0x00007ffc5f8a1013 in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#9  0x00007ffc5f8a0381 in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#10 0x00007ffc5f88a971 in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#11 0x00007ffc5ee90a8e in amdxc64!OpenShimInterface ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#12 0x00007ffc5eebc151 in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#13 0x00007ffc5eebb714 in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#14 0x00007ffc5eeba21e in amdxc64!GetSettingsBlobsAll ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#15 0x00007ffc5ee5051b in amdxc64!AmdExtD3DCreateInterface ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#16 0x00007ffc5ee92409 in amdxc64!OpenShimInterface ()
   from /cygdrive/c/WINDOWS/System32/DriverStore/FileRepository/u0401992.inf_amd64_46fb5d1d0dd76dfd/B401180/amdxc64.dll
#17 0x00007ffc8f7b07b3 in d3d12core!D3D12GetInterface () from /cygdrive/c/WINDOWS/SYSTEM32/D3D12Core.dll
#18 0x00007ffc8f73e33a in d3d12core!D3D12GetInterface () from /cygdrive/c/WINDOWS/SYSTEM32/D3D12Core.dll
#19 0x00007ffc8f721b23 in d3d12core!D3D12GetInterface () from /cygdrive/c/WINDOWS/SYSTEM32/D3D12Core.dll
#20 0x00007ffc8f704f1c in d3d12core!D3D12GetInterface () from /cygdrive/c/WINDOWS/SYSTEM32/D3D12Core.dll
#21 0x00007ffc8f9c5a67 in d3d12!GetBehaviorValue () from /cygdrive/c/WINDOWS/SYSTEM32/d3d12.dll
#22 0x00007ffc8f7159c8 in d3d12core!D3D12GetInterface () from /cygdrive/c/WINDOWS/SYSTEM32/D3D12Core.dll
#23 0x00007ffc7cdef16e in ?? () from /cygdrive/z/Msys64/home/User/workspace/sm64rt/build/us_pc/rt64lib.dll
#24 0x00007ffc7cdf8526 in rt64lib!RT64_GetLastError ()
   from /cygdrive/z/Msys64/home/User/workspace/sm64rt/build/us_pc/rt64lib.dll
#25 0x00007ffc7cdf4c98 in rt64lib!RT64_GetLastError ()
   from /cygdrive/z/Msys64/home/User/workspace/sm64rt/build/us_pc/rt64lib.dll
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x00007ffc7cdf99da in rt64lib!RT64_CreateDevice ()
   from /cygdrive/z/Msys64/home/User/workspace/sm64rt/build/us_pc/rt64lib.dll
#27 0x00000001400d92a1 in gfx_rt64_wapi_init(char const*) ()
#28 0x00000001400d0b28 in gfx_init ()
#29 0x00000001400bca90 in main_func ()
#30 0x00000001400bcbbe in SDL_main ()
#31 0x000000014010afce in main_getcmdline ()
#32 0x00000001400012ee in __tmainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:267
#33 0x00000001400013e6 in WinMainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:157
```

**Comment by landesherr** [comment]
OK, this looks like a driver issue. 24.4.1 drivers don't have this issue. Sorry for the noise.
